name: CI Pipeline

on:
  workflow_dispatch:  # Allows manual trigger from the Actions tab
  push:
    branches: [master]  # Trigger on pushes to the master branch
  pull_request:
    branches: [master]  # Trigger on PRs targeting the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Java Development Kit (JDK) with Java 17
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # Step 3: Install Android SDK Command-Line Tools
      - name: Install Android SDK Command-Line Tools
        run: |
          mkdir -p $HOME/Android/Sdk
          export ANDROID_HOME=$HOME/Android/Sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          sdkmanager --install "cmdline-tools;latest" > /dev/null

      # Step 4: Accept All Android SDK Licenses
      - name: Accept Android SDK Licenses
        run: |
          export ANDROID_HOME=$HOME/Android/Sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          yes | sdkmanager --licenses > /dev/null || echo "License acceptance failed, but continuing."

      # Step 5: Cache Gradle Dependencies
      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 6: Build and Run Unit Tests
      - name: Build and Run Unit Tests
        run: ./gradlew clean test

      # Step 7: Build APKs
      - name: Build APK and Test APK
        run: ./gradlew assembleDebug assembleAndroidTest

      # Step 8: Run Instrumented Tests on Emulator
      - name: Run instrumented tests on emulator
        uses: ReactiveCircus/android-emulator-runner@v2.34.0
        with:
          api-level: 30
          target: 'default'
          emulator-options: '-no-window -gpu swiftshader_indirect'
          script: ./gradlew connectedAndroidTest
          arch: x86
          cores: 2
          avd-name: test
          force-avd-creation: true
          emulator-boot-timeout: 600
          disable-animations: true

      # Step 9: Archive Test Results
      - name: Archive Instrumented Test Results
        uses: actions/upload-artifact@v4.6.2
        with:
          name: instrumented-test-reports
          path: app/build/reports/androidTests/connected
