name: CI Pipeline

on:
  workflow_dispatch: # Allows manual triggering from the Actions tab
  push:
    branches: [master]  # Automatically triggers on pushes to the master branch
  pull_request:
    branches: [master] # Automatically triggers on pull requests targeting the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Java Development Kit (JDK) with Java 17
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # Step 3: Cache Gradle Dependencies
      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
          

      # Step 4: Build and Run Unit Tests
      - name: Build and Run Unit Tests
        run: ./gradlew clean test

      - name: List Test Reports Directory
        run: ls -la app/build/reports/tests/testDebugUnitTest

      # Step 5: Archive Unit Test Results
      - name: Archive Unit Test Results
        uses: actions/upload-artifact@v4.6.2
        with:
          name: unit-test-report
          path: app/build/reports/tests/testDebugUnitTest

      # Step 6: Build and run Espresso Test
#      - name: Build and Run Instrumented Test (Espresso)
#        run: ./gradlew connectedAndroidTest

      # This step uses the ReactiveCircus Android Emulator Runner to start an emulator.
      - name: Run instrumented tests on emulator
        uses: ReactiveCircus/android-emulator-runner@v2.34.0
        with:
          api-level: 30              # Choose an API level that's supported by your AVD
          target: 'default'          # Use the default system image target
          emulator-options: '-no-window -gpu swiftshader_indirect'
          script: ./gradlew connectedAndroidTest


      # Step 7: Archive Espresso Test
      - name: Archive Instrumented Test Results
        uses: actions/upload-artifact@v4.6.2
        with:
          name: instrumented-test-reports
          path: app/build/reports/androidTests/connected

