name: CI Pipeline

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Java Development Kit (JDK) with Java 17
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # Step 3: Install Android SDK Command-Line Tools
      - name: Install Android SDK Command-Line Tools
        run: |
          mkdir -p $HOME/Android/Sdk/cmdline-tools/latest
          curl -o cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip cmdline-tools.zip -d $HOME/Android/Sdk/cmdline-tools
          mv $HOME/Android/Sdk/cmdline-tools/cmdline-tools $HOME/Android/Sdk/cmdline-tools/latest

      # Step 4: Set Environment Variables for Android SDK
      - name: Set Environment Variables for Android SDK
        run: |
          export ANDROID_HOME=$HOME/Android/Sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH

      # Step 5: Accept Android SDK Licenses
      - name: Accept Android SDK Licenses
        run: |
          yes | sdkmanager --licenses

      # Step 6: Cache Gradle Dependencies
      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 7: Build and Run Unit Tests
      - name: Build and Run Unit Tests
        run: ./gradlew clean test

      # Step 8: Build APKs
      - name: Build APK and Test APK
        run: ./gradlew assembleDebug assembleAndroidTest

      # Step 9: Run Instrumented Tests on Emulator
      - name: Run instrumented tests on emulator
        uses: ReactiveCircus/android-emulator-runner@v2.34.0
        with:
          api-level: 30
          target: 'default'
          emulator-options: '-no-window -gpu swiftshader_indirect'
          script: ./gradlew connectedAndroidTest
          arch: x86
          cores: 2
          avd-name: test
          force-avd-creation: true
          emulator-boot-timeout: 600
          disable-animations: true

      # Step 10: Archive Test Results
      - name: Archive Instrumented Test Results
        uses: actions/upload-artifact@v4.6.2
        with:
          name: instrumented-test-reports
          path: app/build/reports/androidTests/connected
