name: CI Pipeline

on:
  workflow_dispatch: # Allows manual triggering from the Actions tab
  push:
    branches: [master]  # Automatically triggers on pushes to the master branch
  pull_request:
    branches: [master]  # Automatically triggers on pull requests targeting the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Java Development Kit (JDK) with Java 17
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # Step 3: Cache Gradle Dependencies
      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 4: Build and Run Unit Tests
      - name: Build and Run Unit Tests
        run: ./gradlew clean test

      - name: List Test Reports Directory
        run: ls -la app/build/reports/tests/testDebugUnitTest

      # Step 5: Archive Unit Test Results
      - name: Archive Unit Test Results
        uses: actions/upload-artifact@v4.6.2
        with:
          name: unit-test-report
          path: app/build/reports/tests/testDebugUnitTest

      # Step 5: Start Emulator and Run Tests
      - name: Run Espresso Tests on Emulator
        uses: ReactiveCircus/android-emulator-runner@v2.34.0
        with:
          api-level: 30                      # API level for emulator
          target: 'default'                  # Default Android target system image
          arch: x86                          # Emulator architecture
          cores: 2                           # Number of CPU cores
          avd-name: test                     # Name of the AVD
          force-avd-creation: true           # Force creation of a new AVD
          emulator-boot-timeout: 600         # Timeout for emulator boot in seconds
          emulator-options: '-no-window -gpu swiftshader_indirect'  # Headless mode
          disable-animations: true           # Disable animations for stability
          script: ./gradlew connectedAndroidTest  # Command to run Espresso tests

#      # Step 7: Archive Instrumented Test Results
#      - name: Archive Instrumented Test Results
#        uses: actions/upload-artifact@v4.6.2
#        with:
#          name: instrumented-test-reports
#          path: app/build/reports/androidTests/connected
